version: 1
services:
  - type: web
    name: my-streamlit-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py"
    envVars:
      - key: STREAMLIT_SERVER_PORT
        value: "10000" # or your specific port
